settings = {
    "DisableNagle": True,
    "BannedIPs": [],
    "PrintEnabled": True,
    "UseContentUpdater": False,
    "Maintance": False,
    "MaintanceTime": 300,
    "UpdateURL": "https://t.me/Godzillabrawl",
    "LobbyInfoMsg": "Draco Brawl\nVersion: v55.211\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "DoubleTokenEvent": True,
    "GoldRushEvent": True,
    "BrawlPassSeason": 23,
    "BrawlPassTimer": [2026, 7, 10, 11, 0, 0],
    "BrawlPassTimer2": [2026, 7, 10, 11, 0, 0],    
    "LiliTimer": [2026, 7, 10, 11, 0, 0],
    "CodesForPremium": ["FALSIDEV"],
    "ChallengeEnabled": True,
    "ChallengeLives": 4,
    "ChallengeLogicName": "thrower_challenge",
    "ChallengeVariation": 7,
    "ChallengeName": "Thrower Challenge",
    "ChallengeStages": 3,
    "ChallengeTotalWins": 9,
    "ChallengeMaps": [476, 83, 116, 0, 0, 0, 0, 0, 0, 0],
    "ChallengeMapsWins": [3, 3, 3, 0, 0, 0, 0, 0, 0, 0],
    "ChallengeFinalReward": {"Type": 19, "Amount": 1, "Brawler": [0, 0], "Extra": 637},
    "ChallengeRewards": [{"Win": 1,"Type": 1, "Amount": 100, "Brawler": [0, 0], "Extra": 0}, {"Win": 2, "Type": 1, "Amount": 100, "Brawler": [0, 0], "Extra": 0}, {"Win": 3, "Type": 14, "Amount": 1, "Brawler": [0, 0], "Extra": 0}, {"Win": 4, "Type": 28, "Amount": 250, "Brawler": [0, 0], "Extra": 0}, {"Win": 5, "Type": 28, "Amount": 250, "Brawler": [0, 0], "Extra": 250}, {"Win": 6, "Type": 19, "Amount": 1, "Brawler": [0, 0], "Extra": 636}, {"Win": 7, "Type": 17, "Amount": 500, "Brawler": [0, 0], "Extra": 0}, {"Win": 8, "Type": 17, "Amount": 500, "Brawler": [0, 0], "Extra": 0}, {"Win": 9, "Type": 10, "Amount": 1, "Brawler": [0, 0], "Extra": 0}],
    "Theme": 96, 
    "CreatorsCodesCats": ["Aurum"],
    "Proxy": False,
    "DumpPacket": False,
    "Blacklist": [],
    "DumpMajor": 55
}